### ISSUE TITLE
Основа бота

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#1]
## How To Do?
Создать начальную файловую структуру

```
src/
├─ bot/
│  ├─ bot.py
│  ├─ __main__.py
│  ├─ utils/
│  │  ├─ config.py
.env.example
README.md
.gitignore
```

Реализовать построение приложения бота в файле `src/bot/bot.py` отдельной функцией `create_bot_app()` она должна возвращать экземпляр приложения
https://docs.python-telegram-bot.org/en/stable/telegram.ext.applicationbuilder.html

Создать файл `__main__.py` с запуском бота в режиме `polling`
После изменений бот должен запускаться командой
```
python -m src/bot
```

Наверняка, понадобится использовать переменные окружения, хорошо было бы собрать их в одном месте `config.py`
Используй `python-dotenv`

**Comment by therealestbatiskaf** [comment]
А нужно запускать приложение, т.е. `application.run_polling()`, или именно бота, обращаясь к нему через `application.bot` который возвращает объект класса `Bot`?

Просто я нашёл `Bot.get_updates()`, но как будто это тоже самое, что и `application.run_polling()`

**Comment by TomatoInOil** [comment]
> get_updates()

Это часть процесса polling, а не его вызов. А вот application.run_polling() совмещает в себе и инициализацию, и запуск polling, старт приложения, а также его завершение по некоторым сигналам, например, [KeyboardInterrupt](https://docs.python.org/3/library/exceptions.html#KeyboardInterrupt)
https://docs.python-telegram-bot.org/en/stable/telegram.ext.application.html#telegram.ext.Application.run_polling
