### ISSUE TITLE
Настройка логирования

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#12]
## How To Do?
- Используя рекомендации от разработчиков PTB
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exceptions%2C-Warnings-and-Logging#logging
Настроить логирование в боте.
- Использовать TimedRotatingFileHandler для записи в файл и StreamHandler для вывода в консоль
- Настройки по умолчанию для `TimedRotatingFileHandler` 
```
when = "midnight"
interval = 1
backup_count = 14
encoding = UTF-8
```
## Where? 
`src\bot\utils\logger.py`

**Comment by therealestbatiskaf** [comment]
В примере PTB приводят 2 логгера, 1 для `httpx`, другой для `apscheduler`, нас какой из интересует? Или нас интересует и тот, и тот? (там устанавливают конкретный уровень, для конкретного handler'а как я понял, вот)

Я правда не понимаю по стандарту он будет выдавать `httpx` и `apscheduler`, надо разобраться

Я понял, они есть по стандарту PTB и это просто настройка их уровней, нас какие интересуют?

-------
![Image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/144885477/a6d81532-1ef2-4f6a-ae78-315236ec6566)

**Comment by therealestbatiskaf** [comment]
И ещё один вопрос заодно, логи нужны в опр. папке (по типу `logs` где-нибудь) или можно прям в utils их хранить?

**Comment by TomatoInOil** [comment]
1. Нас интересует установить уровень логирования warning для `httpx`, т.к. это библиотека, с помощью которой совершаются запросы к API Telegram в PTB, логи на уровне `info` для этой библиотеки могут содержать `sensitive data`, например, токен бота, а `apscheduler` у нас в проекте пока что нет и не планируется 
2. Да, было бы хорошо, например, задать вот так
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/44ea5588e76be2a7c67446efeacb60bb1d383960/src/core/config.py#L7-L14
