### ISSUE TITLE
Баг: не работает проверка на существование коливинга

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#134]
Нужно исправить баг:
Если мы создадим коливинг, а потом скроем его из поиска, то когда мы снова через меню зайдём в "Мой коливинг", то перейдём к созданию ещё одного. Дело в том, что запрос получения коливингов с фильтрацией по владельцу и поиск коливинга используют одну и ту же ручку:
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/2e21cca8564660b63a1529436a59f6a99bccab80/src/bot/internal_requests/service.py#L99
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/2e21cca8564660b63a1529436a59f6a99bccab80/src/bot/internal_requests/service.py#L187
Но для поиска важна фильтрация по `is_visible==True`, а в случае получения коливингов пользователя `queryset` по этому полю не должен фильтроваться.

**Comment by ilililililililililililililil** [comment]
@TomatoInOil я правильно понял, что is_visible==True нужно сохранить для второго случая и исключить для первого?

**Comment by TomatoInOil** [comment]
> @TomatoInOil я правильно понял, что `is_visible==True` нужно сохранить для второго случая и исключить для первого?

is_visible должен влиять при поиске коливинга по заданным критериям, а при получении коливингов конкретного пользователя - нет
