### ISSUE TITLE
Ветвь общения profile

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#14]
## How To Do?
Добавить обработку получения, редактирования анкеты пользователя. 
Составлена [state диаграмма](https://www.notion.so/e22157225bd244b1aca403c8e95ebc8b?pvs=4#b073501cc7244f6fac393e9ca0b24b7e) этой ветви, по сути это сценарий, который нужно реализовать
Сейчас можно как точку входа (`entry_point`) задать команду `/profile`, после того, как все ветви меню будут готовы, то объединим их в одну команду
API ещё не реализован, поэтому при разработке можно набросать пока mock обёртку над API и сущности
Вот пример:
```Python
# src/bot/internal_requests/mock.py

async def get_user_profile_by_telegram_id(telegram_id: int) -> UserProfile:
    return UserProfile(name="Иван", age=25, ...)
```
```Python
# src/bot/internal_requests/entities.py

@dataclass
class UserProfile:
    name: str
    age: int
    # Остальные атрибуты 

```
Использование:
```Python
from internal_requests import mock as api_service

async def some_callback_func(update: Update, context: CallbackContext) -> int:
    # Возможно, какой-то код
    user_info = await api_service.get_user_profile_by_telegram_id(update.effective_chat.id)
    # Остальной код
    return STATE
```
## Where?
`src/bot/conversations/profile/`
Рекомендуемая структура
```
profile/
├─ callback_funcs.py   <- функции обратного вызова*
├─ handler.py          <- определение СonversationHandler
├─ template.py         <- константы с текстом сообщений
```
`*` функции вызываемые обработчиками

`src/bot/internal_requests/mock.py`
`src/bot/internal_requests/entities.py`

**Comment by Dadyx85** [comment]
Даниил, привет. Сделал пока следующее: вынес кнопки ветки Profile в модуль buttons.py, состояние бота в states.py, сообщения оставил в templates.py. Не совсем понял,что должно быть в модуле callback. В handler? если я правильно думаю, должны быть обработчики сообщений?
