### ISSUE TITLE
Добавление rate-limiter против превышения лимитов Telegram на отправку сообщений

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#159]
# Why?
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits
# How To Do?
Нужно при сборке application добавить rate_limiter: [AIORateLimiter](https://docs.python-telegram-bot.org/en/stable/telegram.ext.aioratelimiter.html)

# Where?
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/d5fe000cefc2c95fd134d5161860a2ec307e9515/src/bot/bot.py#L27-L33

**Comment by Andrey-66** [comment]
Rate-limiter я подключил (вроде работает, ограничивает количество запросов 30 в секунду), возникает вопрос в необходимости приоритета каких-либо сообщений, т.е. чтобы какие-то из сообщений обходили их очередь и доходили до пользователя приоритетно (или наоборот с меньшим приоритетом, не препятствуя другим).

**Comment by TomatoInOil** [comment]
@Andrey-66 Да, приоритетность нам понадобится, но когда мы будем работать над рассылками, чтобы их приоритет был ниже и не препятствовал основным взаимодействиям с ботом. 
Вот здесь можно посмотреть пример того, что будет нам нужно, второй листинг этого раздела: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits#ptbs-rate-limiting-mechanism
Но это другая задача, создавай PR.
