### ISSUE TITLE
Реализовать обёртку над ручкой, что создаёт жалобы

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#160]
# Why?
Это нужно для реализации следующего функционала: https://github.com/orgs/Studio-Yandex-Practicum/projects/30/views/1?pane=issue&itemId=64413949
# How To Do?
Есть класс, который содержит методы, обращающиеся к API
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/d5fe000cefc2c95fd134d5161860a2ec307e9515/src/bot/internal_requests/service.py#L28-L31

Нужно добавить метод, который обращается к этой ручке
Документация: http://127.0.0.1:8000/api/schema/swagger-ui/#/reports/reports_create
# Where?
`src/bot/internal_requests/service.py`

**Comment by StDemidov** [comment]
Я не понимаю, на что ругается блэк, откомментил в пулл реквесте
