### ISSUE TITLE
D-1: Улучшить сообщение о некорректно введённом возрасте

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#184]
Если при регистрации ввести возраст неправильно, то выдаётся сообщение

`"Введи число от 18 до 99:"`

Нужно уточнить текст так, чтобы он был следующего вида:

`"Можно ввести возраст от 18 до 99 лет."`

**Comment by ilililililililililililililil** [comment]
@TomatoInOil привет, ты уверен, что это сообщение сейчас выводится для возраста?

по коду сообщение про возраст это "Введите свой возраст в формате двузначного числа (например - 25)."

а твой вариант - используется только в частях относящихся к стоимости


![Image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/110520607/a81077ef-a910-4a1d-8021-db3fd4905887)
![Image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/110520607/f9a179c5-dd1c-4f99-a864-3fac6cfe4748)

**Comment by ilililililililililililililil** [comment]
@TomatoInOil как обсудили - заменить надо указанное мной сообщение 
"Введите свой возраст в формате двузначного числа (например - 25)."

на 

"Можно ввести возраст от 18 до 99 лет."
