### ISSUE TITLE
D-2: Автоматическое удаление тире вокруг имени

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#185]
## Задача
Нужно реализовать автоматическое удаление тире в начале и конце значений, вводимых для поля "Имя" при регистрации пользователя. 

## Описание
В текущей версии приложения поле "Имя" принимает значения с тире в начале и/или конце имени. Например, такие значения как "-Иван" и "Иван-" считаются допустимыми. Необходимо настроить автоматическое удаление тире в начале и конце введённого значения перед отправкой запроса к API.

- При вводе данных в поле "Имя", если значение начинается с тире, оно должно быть удалено. (`-Иван` -> `Иван`)
- При вводе данных в поле "Имя", если значение заканчивается на тире, оно должно быть удалено. (`Иван-` -> `Иван`)
- Первые два пункта вместе. (`-Иван-` -> `Иван`)
- Внутренние тире в значении поля "Имя" должны оставаться без изменений (например, значение "Александра-Виктория" не должно изменяться).

**Comment by ilililililililililililililil** [comment]
@TomatoInOil мне кажется, правильнее обрабатывать имя на стороне api, а не до отправки в api.
