### ISSUE TITLE
Bot: Прикрепление к коливингу до 5 фотографий

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#60]
**UPD:** По этой задаче уже создана ветка и PR другим разработчиком, но я рекомендую создать новую ветку, потому что каких-то ценных наработок там нет 

### Why?

В боте сейчас к коливингу можно прикрепить только 1 фотографию, но нужно до 5. 
**UPD:** Также сейчас не получится изменить изображения.

### How To Do?

[Немного про ограничения](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-deal-with-a-media-group): Если пользователь отправляет `media group` (несколько сгруппированных фотографий), то для нас это выглядит как несколько сообщений. 

По ссылке так же описаны идеи, как это можно решить. Мне нравится идея “**Manual approach**", но с использованием кнопки, например, “сохранить”. 

**UPD:** В ветке профиля уже реализована нужная логика, а ещё также там реализовано изменение изображений, нужно для коливинга сделать то же самое

Также необходимо внести изменения в State диаграмму для поддержания её в актуальном состоянии.

### Where?

`src/bot/conversations/coliving`

**Comment by VladErm91** [comment]
Добавил автоматическую обработку сохранения если загружено 5 фото
