### ISSUE TITLE
Workflow для деплоя на тестовый сервер

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#63]
### How To Do?

На сервер нужно установить docker

Для образов docker использовать `ghcr.io`

Вот примеры
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/develop/.github/workflows/deploy_stage.yaml

https://github.com/Studio-Yandex-Practicum/you_can_bot/blob/develop/.github/workflows/deploy_workflow.yml

### Where?

`.github/workflows/deploy_workflow.yml`

**Comment by QuiShimo** [comment]
Установил на сервер docker
