### ISSUE TITLE
Рефакторинг ReportMatchViewTests

### ISSUE THREAD

**Issue by TomatoInOil** [Studio-Yandex-Practicum/coliving_bot#83]
Требуется провести рефакторинг тестов для `ReportMatchView`. В ходе написания тестов для `ProfileSearchView` были выявлены оптимизации, которые также необходимо применить к тестам для `ReportMatchView`. Задача включает в себя анализ текущих тестов, нахождение и применение новых оптимизаций, применение уже выявленных.

**Comment by ilililililililililililililil** [comment]
привет, 

Посмотри мою версию плз, напиши, если увидишь, где можно лучше 

хотел дополнительно еще оптимизировать определение 
cls.expected_match_data_for_user_*

через 
        ExpMatchData = namedtuple("ExpMatchData",
                                  [cls.TID_T, cls.NAME_T, cls.AGE_T, cls.L_T])

но не уверен, стоит ли ...
